name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: src/github.com/pinzolo/secevsubid

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
        env:
          GOPATH: ${{ runner.workspace }}/secevsubid

      - name: Build
        run: cd ${{ runner.workspace }}/secevsubid/src/github.com/pinzolo/secevsubid && go build -v ./...
        env:
          GOPATH: ${{ runner.workspace }}/secevsubid

      - name: Execute tests
        run: cd ${{ runner.workspace }}/secevsubid/src/github.com/pinzolo/secevsubid && go test -v ./...
        env:
          GOPATH: ${{ runner.workspace }}/secevsubid
