name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.18'
          - '1.19'
          - '1.20'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: src/github.com/pinzolo/secevsubid

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
        env:
          GOPATH: ${{ github.workspace }}

      - name: Build with ${{ matrix.go-version }}
        run: cd ${{ github.workspace }}/src/github.com/pinzolo/secevsubid && go build -v ./...
        env:
          GOPATH: ${{ github.workspace }}

      - name: Test with ${{ matrix.go-version }}
        run: cd ${{ github.workspace }}/src/github.com/pinzolo/secevsubid && go test -v ./...
        env:
          GOPATH: ${{ github.workspace }}
